# ===============================
# PATHS
# ===============================
paths:
  train_data: "src/data/seg_train/seg_train"
  test_data: "src/data/seg_test/seg_test"
  predict_data: "src/data/seg_pred/seg_pred"
  model_save_path: "artifacts/best_model.h5"
  history_save_path: "artifacts/training_history.json"
  output_metrics: "artifacts/metrics_report.txt"

# ===============================
# MODEL PARAMETERS
# ===============================
model:
  architecture: "ResNet152V2"
  input_shape: [128, 128, 3]       # Reduced to save RAM
  num_classes: 6
  pretrained: true
  pooling: "avg"

# ===============================
# TRAINING PARAMETERS
# ===============================
training:
  batch_size: 8                    # Reduced from 32
  epochs: 1
  learning_rate: 0.0001
  optimizer: "Adam"
  loss_function: "categorical_crossentropy"
  metrics: ["accuracy"]

# ===============================
# CALLBACKS
# ===============================
callbacks:
  model_checkpoint:
    monitor: "val_accuracy"
    save_best_only: true
    mode: "max"
    verbose: 1

# ===============================
# AUGMENTATION (if any)
# ===============================
augmentation:
  use_augmentation: true
  rotation_range: 20
  width_shift_range: 0.2
  height_shift_range: 0.2
  zoom_range: 0.2
  horizontal_flip: true
  fill_mode: "nearest"
